=== blogspeare72/tranq_server/app/assets/json_schema/rest_checker/oauth_file_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "API Compliance OAUTH Parameters file",
    "type": "object",
    "additionalProperties" : false,
    "required" : [
	"authorize_endpoint",
	"base_uri",
	"callback_uri",
	"client_id",
	"client_secret",
	"code",
	"refresh_token",
	"scope",
	"token_endpoint"
    ],
    "properties" : {
	"access_token" : {
	    "type" : "string",
	    "title": "Previously provided access token to the scope; access tokens are usually valid for a short period of time.  Tranquilize will use the token end point, refresh token or code to request a new access token, if required."
	},
	"authorize_endpoint" : {
	    "type" : "string",
	    "title": "The endpoint for authorization, which when combined with the base uri provides the concentrate absolute URI to authorize the client."
	},
	"base_uri" : {
	    "type"   : "string", 
	    "format" : "uri",
	    "title"  : "The base URI of the authorization server."
	},
	"callback_uri" : {
	    "type"   : "string", 
	    "format" : "uri",
	    "title"  : "The callback location for the OAUTH server to send the a new code, if needed."
	},
	"client_id" : {
	    "type" : "string",
	    "title": "The client application id known to the OAUTH server."
	},
	"client_secret" : {
	    "type" : "string",
	    "title": "The client secret, used to prove to the OAUTH server that this client can have a token."
	},
	"code" : {
	    "type"   : "string",
	    "title"  : "OAUTH Client code used to obtain the access token."
	},
	"refresh_token" : {
	    "type" : "string",
	    "title": "If the access token expires, Tranquilize will use the refresh token to fetch a new access token."
	},
	"scope" : {
	    "type"   : "string",
	    "title"  : "The scope or area of requested access; for Oracle this could correspond to a high level context, e.g., a group of functionally related resources."
	},
	"token_endpoint" : {
	    "type"   : "string",
	    "title"  : "The endpoint to access the token, which together with the base URI form the concentrate absolute URI to collect the authorization token."
	}

    }
}

=== blogspeare72/tranq_server/public/1/1_oauth.json
{
  "base_uri": "https://gatekeeper.staging.cloud.vitrue.com",
  "client_id": "81f88983a6b640e651d5d0774409bb1985f502fffc79f8081f31421b19342bf3",
  "client_secret": "ec7df24010268a1e3d7ada2c6fd2d3e79093583d98029ea0d04ad0311a6ad94c",
  "callback_uri": "http://localhost:3000/gatekeeper/callback",
  "authorize_endpoint": "/oauth/authorize",
  "token_endpoint": "/oauth/token",
  "scope": "admin",
  "access_token": "c08167948e9f82f7b8ab0ddb0c2971b8ecd6b38e80f8ca7c0049669558274fbb",
  "refresh_token": "851d0276594bad2aa53e617f941a8bf86883ca53c54e6d78e9e0f6de5e779817",
  "code": "030f489ea27960695aaa14df96bc59c1113e61c6420311a3eb82adffd9d6d998"
}
